{
 "title": "ETH Blocks Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "SyncCommitteeEpoch",
    "label": "Sync Committee Epoch",
    "query": {
     "query": "label_values(CurrentSyncCommitteeEpoch, epoch)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Global MEV Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "24h Global Block Proposals",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(TotalRelayBlocksProposed[24h])",
     "legendFormat": "{{relay}}"
    }
   ]
  },
  {
   "title": "Global Average MEV Reward",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "AvgRelayerRewards", "legendFormat": "{{relay}}" }
   ]
  },
  {
   "title": "Total Global MEV Rewards",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "RelayTotalRewards", "legendFormat": "{{relay}}" }
   ]
  },
  { "title": "Validator Block Proposals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Total Blocks Proposed By Relay",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "RelayBlocksProposed", "legendFormat": "{{relay}}" }
   ]
  },
  {
   "title": "Blocks Proposed Per Relay in the last 10 mins",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "increase(RelayBlocksProposed[10m])",
     "legendFormat": "{{relay}}"
    }
   ]
  },
  {
   "title": "Blocks Proposed By Relay in the last 10 mins",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "increase(RelayBlocksProposed[10m])",
     "legendFormat": "{{relay}}"
    }
   ]
  },
  {
   "title": "Blocks Proposed By Validator in the last 10 mins",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(ValidatorBlocksProposed[10m]) > 0",
     "legendFormat": "{{public_key}}"
    }
   ]
  },
  {
   "title": "Local Block Proposals in the last 10 minutes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "increase(RelayBlocksProposed{relay=\"Unknown\"}[10m])",
     "legendFormat": "{{public_key}}"
    }
   ]
  },
  {
   "title": "Empty Blocks Proposed By Validator in the last 10 mins",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "targets": [
    {
     "expr": "increase(EmptyBlockProposals[10m]) > 0",
     "legendFormat": "{{public_key}}"
    }
   ]
  },
  {
   "title": "Missed Blocks Proposed By Validator in the last 10 mins",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
   "targets": [
    {
     "expr": "increase(MissedBlockProposals[10m]) > 0",
     "legendFormat": "{{public_key}}"
    }
   ]
  },
  { "title": "Validator MEV Rewards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Total MEV Validator Rewards",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "TotalValidatorRewards", "legendFormat": "{{relay}}" }
   ]
  },
  {
   "title": "Average MEV Reward",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "AvgValidatorRewards", "legendFormat": "{{relay}}" }
   ]
  },
  { "title": "Sync Committee", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Sync Committee Participation %",
   "type": "stat",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ValidatorSyncParticipated{epoch=\"$SyncCommitteeEpoch\"} / (ValidatorSyncParticipated{epoch=\"$SyncCommitteeEpoch\"} + ValidatorSyncMissed{epoch=\"$SyncCommitteeEpoch\"})) * 100",
     "legendFormat": "{{public_key}}"
    }
   ]
  },
  {
   "title": "Sync Committee Missed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "ValidatorSyncMissed{epoch=\"$SyncCommitteeEpoch\"}",
     "legendFormat": "{{public_key}}"
    }
   ]
  }
 ]
}